name: Build and Deploy Express App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Production .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "AWS_S3_BUCKET=my-express-app-builds-uniqueid" >> .env
          echo "AWS_REGION=ap-south-1" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}" >> .env
          echo "SES_FROM_EMAIL=${{ secrets.SES_FROM_EMAIL }}" >> .env

      - name: Zip the application files
        run: zip -r website.zip . -x "*.git*"

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::260543925645:role/GitHubActions-Deploy-Role
          aws-region: ap-south-1

      - name: Upload Artifact to S3
        run: |
          aws s3 cp website.zip s3://my-express-app-builds-uniqueid/website.zip

      - name: Trigger Auto Scaling Group Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name express-app-asg \
            --preferences '{"MinHealthyPercentage": 50}'